### ISSUE TITLE
Review mappluto_bbl values

### ISSUE THREAD

**Issue by mattyschell** [mattyschell/geodatabase-buildings-condoetl#6]
A colleague at NYC Emergency management reports discrepancies comparing mappluto_bbl values we produce here to actual values in MapPLUTO.  Seems bad!

Quickly reviewing these I see a couple of possibilities to track down.  Sometimes we have multiple condos on a single building footprint and we remove duplicates at random.  Let's revisit this decision, and I use the word "decision" loosely.

We also may have cases where the condo value reported in MapPLUTO is different from the value we fetch from the live the Dept of Finance condo dataset.  We chose the Dept of Finance value because it seemed like it would be the most truthy.  But if the point of this repo is to provide helpful values that join to MapPLUTO then why are we populating the buildings dataset with good but ultimately not useful values?

**Comment by mattyschell** [comment]
[oti_buildings_wrong_mappluto_bbls_20220915.csv](https://github.com/mattyschell/geodatabase-buildings-condoetl/files/9608848/oti_buildings_wrong_mappluto_bbls_20220915.csv)

**Comment by mattyschell** [comment]
The SQL at the center of this investigation:

https://github.com/mattyschell/geodatabase-buildings-condoetl/blob/d5c2d84d98aac535067f629e3fd83dad20b26c35/condoloader.py#L103

**Comment by mattyschell** [comment]
Related #5

**Comment by wmc281** [comment]
Hi @mattyschell. You may have already spotted this. 
In addition to the condo issue, there are also a handful of records where the block/lot are in sync, but the first digit borough code in BBL values are different. That is strange.
![image](https://user-images.githubusercontent.com/90013103/191342379-3c26f155-7b66-42f3-bf1e-032317cf0246.png)

**Comment by mattyschell** [comment]
Thank you formerly anonymous colleague @wmc281 . Great to see you helping us out here on GitHub.  I've responded to your additional issue, which I had definitely not yet spotted, with the best emoji GitHub has to offer for this. 

Thanks again for these reports, feel free to open up new issues or comment on existing ones any time you like.

**Comment by mattyschell** [comment]
https://github.com/mattyschell/geodatabase-buildings/issues/14
 
Building bin/bbls in different boros is a known issue, resolution TBD.

**Comment by mattyschell** [comment]
I reviewed this excellent list and I see three distinct issues.

1. A couple of out of synch values between OTI mappluto_bbl and DCP mappluto.  This is inevitable.  These are almost always xxxxxx75xx bbls that have been created or destroyed recently.
2. A larger category of buildings that do not exist on tax lots.  They're in easements  and so on we know these they are ok.
3. Most importantly:  Most numerous are building base_bbls that do not exist in the Dept. of Finance tax lots or in Dept of City Planning Pluto.  These are bad building bbls, they were typo'd or the tax lots no longer exist.

We will upgrade https://github.com/mattyschell/geodatabase-buildings-bbl-qa to flag category 3.  I am closing this issue under this repository.

Thanks again @wmc281 great QA here! Stay tuned.
